spring.application.name=EcoMarket
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//ecodb.cbyd4ixtkjlq.us-east-1.rds.amazonaws.com:1521/TEST_A
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=ADMIN
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.mvc.cors.enabled=true
# JWT CONFIG
jwt.secret=ESTA_ES_UNA_CLAVE_DE_64_CHARS_MINIMO_GENERADA_ALEATORIAMENTE_PARA_JWT_XD123456789
# 24 horas en milisegundos
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.com.example.EcoMarket.security=DEBUG
