# Conexion directa a RDS (prueba rapida).
# NOTA: He asumido que el nombre de la base de datos en la instancia RDS es "ecomarket".
# Si tu base tiene otro nombre, reemplaza 'ecomarket' por el nombre correcto abajo.
spring.datasource.url=jdbc:mysql://database-ecomarket.cbyd4ixtkjlq.us-east-1.rds.amazonaws.com:3306/ecomarket?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=ecomarket234.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Para desarrollo: permite que hibernate cree/ajuste tablas (cambiar en produccion)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false

# Pool (Hikari por defecto)
spring.datasource.hikari.maximum-pool-size=10
